fix: recebe username como input
betrybe/jest-evaluator-action pull request #15
Opened 2021-01-22 12:47 UTC by eucleciojosias

Devido as alterações na [LEARN-869](https://trybe.atlassian.net/browse/LEARN-869?atlOrigin=eyJpIjoiNDZlNGJlYTljYzM2NDRhZmI0OGU3Njk1MGYwZGJmN2UiLCJwIjoiaiJ9), no qual o _workflow_ é executado via `dispatch`, a _envvar_ `GITHUB_ACTOR` é o Github App de Selfhosted então é necessário passar o **username** via **input**.

2021-01-25 12:29 UTC, gknedo approved these changes

2021-01-25 15:42 UTC, jeanpsv approved these changes

2021-01-26 16:53 UTC, inaC requested changes

2021-01-26 16:53 UTC, inaC commented on README.md
> +Pull Request author username
Esse input é obrigatório, não?
```suggestion
**Required**

Pull Request author username
```

2021-01-26 16:53 UTC, inaC commented on README.md
> +### `pr_author_username`
Se esse input for obrigatório, seria interessante atualizar em como consumir a action com esse input, nas seções [`Usage example`](https://github.com/betrybe/jest-evaluator-action#usage-example) e [`How to get result output`](https://github.com/betrybe/jest-evaluator-action#how-to-get-result-output), não?

2021-01-26 17:31 UTC, inaC approved these changes

2021-02-01 16:33 UTC, hurrycaner approved these changes

2021-02-01 22:31 UTC, merged